name: BuildWindowsEXE

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller
        pyinstaller --onefile main.py
        ls dist
        
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: dist/main.exe
